name: Build and Deploy

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install xz-rust
      run: |
        cd webapp/xz-rust
        cargo install wasm-pack
        wasm-pack build

    - name: Install & build webapp
      run: |
        cd webapp/web
        npm install
        PUBLIC_URL="https://truebrain.github.io/OpenTTD-savegame-reader/" npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        branch: gh-pages
        folder: webapp/web/build
