name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        include:
          - python-version: "3.8.2"
            os: "ubuntu-24.04"
          - python-version: "3.12.0"
            os: "ubuntu-24.04"
          - python-version: "3.8.2"
            os: "macos-13"
          - python-version: "3.12.0"
            os: "macos-13"
          - python-version: "3.8.2"
            os: "windows-2019"
          - python-version: "3.12.0"
            os: "windows-2019"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          # Pin to be able to install older Python
          version: "0.6.17"
          python-version: ${{ matrix.python-version }}
          activate-environment: true
      - name: "Install python dependencies"
        run: |
          uv pip install ".[ci]"
      - name: "Run tests"
        run: |
          pytest --cov
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
