name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        include:
          - python-version: "3.8.0"
            os: "ubuntu-20.04"
          - python-version: "3.12.0"
            os: "ubuntu-20.04"
          - python-version: "3.8.0"
            os: "macos-12"
          - python-version: "3.12.0"
            os: "macos-12"
          - python-version: "3.8.0"
            os: "windows-2019"
          - python-version: "3.12.0"
            os: "windows-2019"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: '${{ matrix.python-version }}'
      - name: "Install 7z"
        if: matrix.os == 'macos-13'
        run: |
           brew install p7zip
      - name: "Install python dependencies"
        run: |
          pip install ".[ci]"
      - name: "Run tests"
        run: |
          pytest --cov
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
